services:
  db:
    image: postgres:15
    container_name: ktzh_db
    environment:
      POSTGRES_DB: ktzh
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit_app:
    build: .
    container_name: ktzh_back
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ktzh

volumes:
  postgres_data:
