version: "3.8"

services:
  db:
    image: postgres:15
    container_name: ktzh_db
    restart: always
    environment:
      POSTGRES_DB: ktzh
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  streamlit_app:
    build: .
    container_name: ktzh_back
    restart: always
    depends_on:
      - db
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.baseUrlPath=back
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ktzh

  gateway:
    image: nginx:alpine
    container_name: ktzh_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - streamlit_app

volumes:
  postgres_data:
